### ISSUE TITLE
Error thrown from webhook

### ISSUE THREAD

**Issue by Firesphere** [chriswep/plugin-gitea-webhook#2]
I'm getting this error:
```
<br />
<b>Fatal error</b>:  Uncaught TypeError: Symfony\Component\EventDispatcher\EventDispatcher::dispatch(): Argument #1 ($event) must be of type object, string given, called in /var/www/app/plugins/GiteaWebhook/WebhookHandler.php on line 118 and defined in /var/www/app/vendor/symfony/event-dispatcher/EventDispatcher.php:48
Stack trace:
#0 /var/www/app/plugins/GiteaWebhook/WebhookHandler.php(118): Symfony\Component\EventDispatcher\EventDispatcher-&gt;dispatch()
#1 /var/www/app/plugins/GiteaWebhook/WebhookHandler.php(73): Kanboard\Plugin\GiteaWebhook\WebhookHandler-&gt;handleCommit()
#2 /var/www/app/plugins/GiteaWebhook/WebhookHandler.php(54): Kanboard\Plugin\GiteaWebhook\WebhookHandler-&gt;handlePush()
#3 /var/www/app/plugins/GiteaWebhook/Controller/WebhookController.php(28): Kanboard\Plugin\GiteaWebhook\WebhookHandler-&gt;parsePayload()
#4 /var/www/app/app/Core/Controller/Runner.php(77): Kanboard\Plugin\GiteaWebhook\Controller\WebhookController-&gt;handler()
#5 /var/www/app/app/Core/Controller/Runner.php(31): Kanboard\Core\Controller\Runner-&gt;executeController()
#6 /var/www/app/index.php(9): Kanboard\Core\Controller\Runner-&gt;execute()
#7 {main}
  thrown in <b>/var/www/app/vendor/symfony/event-dispatcher/EventDispatcher.php</b> on line <b>48</b><br />
```

**Comment by Firesphere** [comment]
It seems the dispatcher order of arguments has switched around...

**Comment by chriswep** [comment]
is now fixed in master (compatibility with kanboard >1.2.31)
